### ISSUE TITLE
Thompson /w commando perk

### ISSUE THREAD

**Issue by AkselAllas** [poosh/KF-ScrnBalance#17]
Incendiary Thompson gets bonus ammo /w Commando perk, but doesn't get damage bonus or damage counted towards perk.

20 round Thompson is my favourite weapon in the game and I don't see a reason to remove it from Commando. I like the idea to make it Incendiary, but it would make sense to keep the cross perk option for Commando.

Especially with tactical reload, the weapon feels so fun to play with commando.

**Comment by AkselAllas** [comment]
Also, I'm loving the mod! And the KF1/KF2 review episodes on YT are excellent aswell!

**Comment by poosh** [comment]
You can give Commando bonuses to Inc. Thompson by adding this line to ScrnBalanceSrv.ini:
```ini
PerkedWeapons=3:ScrnBalanceSrv.ScrnThompsonInc
```

**Comment by AkselAllas** [comment]
Adding the line worked :)

But how could I also edit e.g. `ScrnThompsonInc.uc`? Does it need compiling? 
Also can I get working Discord link pls?

And have you thought about working with Tripwire to get ScrNMod released in original KF1 as like "KF Remastered" or something?

**Comment by poosh** [comment]
The best way to modify the weapon is to create a separate package and extend the weapon class there. For example:
```
// MyPackage/Classes/MyScrnThompson.uc
class MyThompson extends ScrnThompsonInc;

// put your modifications here
```

Then do the same with the pickup class:
```
class MyThompsonPickup extends ScrnThompsonIncPickup;
```

Compile the package, then add your weapon to ServerPerks.ini:
```ini
TraderInventory=3:MyPackage.MyThompsonPickup
```
