### ISSUE TITLE
Translation system

### ISSUE THREAD

**Issue by Blueberryy** [poosh/KF-ScrnBalance#23]
I don't know if that's possible for mutators due to lack of KF code documentation but i would like to help with Russian translation if you can make custom translation system.

**Comment by ivanmagadan** [comment]
https://github.com/ivanmagadan/ScrnBundle-RUS/tree/main/System

**Comment by poosh** [comment]
> https://github.com/ivanmagadan/ScrnBundle-RUS/tree/main/System

^ this
