### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by dtd123123123** [poosh/KF-ScrnBalance#25]
The features of ScrnBalance are excellent. I’m making good use of them. However, I do have one question.

After loading the game, the memory usage rises to around 1.3 to 1.4 GB. Because of this, it seems that my friends or teammates often experience crashes while playing the game.

Is there a way to reduce the memory usage?

**Comment by poosh** [comment]
1-1.5 GB memory usage is normal for this game mode. People are crashing not because they are running out of memory. Crash reasons are still unknown - probably something withing the engine. Alt-tabbing during the game increases the chance of getting a crash.
